package com.dapeng.springboot.api;

      import com.github.dapeng.core.*;
      import com.github.dapeng.org.apache.thrift.*;
      import java.util.ServiceLoader;
      import com.dapeng.springboot.api.UserServiceCodec.*;
      import com.dapeng.springboot.api.UserServiceSuperCodec.*;
      import com.dapeng.springboot.api.service.UserService;

      /**
       * Autogenerated by Dapeng-Code-Generator (2.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

      **/
      public class UserServiceClient implements UserService{
      private final String serviceName;
      private final String version;

      private SoaConnectionPool pool;
      private final SoaConnectionPool.ClientInfo clientInfo;

      public UserServiceClient() {
        this.serviceName = "com.dapeng.springboot.api.service.UserService";
        this.version = "1.0.0";

        ServiceLoader<SoaConnectionPoolFactory> factories = ServiceLoader.load(SoaConnectionPoolFactory.class,getClass().getClassLoader());
        this.pool = factories.iterator().next().getPool();
        this.clientInfo = this.pool.registerClientInfo(serviceName,version);
      }

      public UserServiceClient(String serviceVersion) {
        this.serviceName = "com.dapeng.springboot.api.service.UserService";
        this.version = serviceVersion;

        ServiceLoader<SoaConnectionPoolFactory> factories = ServiceLoader.load(SoaConnectionPoolFactory.class,getClass().getClassLoader());
        this.pool = factories.iterator().next().getPool();
        this.clientInfo = this.pool.registerClientInfo(serviceName,version);
      }

      
          
            /**
            * 
            **/
            
              public String sayHello(String name) throws SoaException{

              String methodName = "sayHello";

              sayHello_args sayHello_args = new sayHello_args();
              sayHello_args.setName(name);
                

              sayHello_result response = pool.send(serviceName,version,"sayHello",sayHello_args, new SayHello_argsSerializer(), new SayHello_resultSerializer());

              
                  
                      return response.getSuccess();
                    
                
            }
            
          

        
          
            /**
            * 
            **/
            
              public com.dapeng.springboot.api.domain.User getUser(String id) throws SoaException{

              String methodName = "getUser";

              getUser_args getUser_args = new getUser_args();
              getUser_args.setId(id);
                

              getUser_result response = pool.send(serviceName,version,"getUser",getUser_args, new GetUser_argsSerializer(), new GetUser_resultSerializer());

              
                  
                      return response.getSuccess();
                    
                
            }
            
          

        

      /**
      * getServiceMetadata
      **/
      public String getServiceMetadata() throws SoaException {
        String methodName = "getServiceMetadata";
        getServiceMetadata_args getServiceMetadata_args = new getServiceMetadata_args();
        getServiceMetadata_result response = pool.send(serviceName,version,methodName,getServiceMetadata_args, new GetServiceMetadata_argsSerializer(), new GetServiceMetadata_resultSerializer());
        return response.getSuccess();
      }

      /**
      * echo
      **/
      public String echo() throws SoaException {
        String methodName = "echo";
        echo_args echo_args = new echo_args();
        echo_result response = pool.send(serviceName,version,methodName,echo_args, new echo_argsSerializer(), new echo_resultSerializer());
        return response.getSuccess();
      }


    }
    