package com.dapeng.springboot.api;
        import com.dapeng.springboot.api.domain.serializer.*;

        import com.github.dapeng.core.*;
        import com.github.dapeng.org.apache.thrift.*;
        import com.github.dapeng.org.apache.thrift.protocol.*;

        import com.github.dapeng.core.definition.SoaServiceDefinition;
        import com.github.dapeng.core.definition.SoaFunctionDefinition;

        import java.io.BufferedReader;
        import java.io.InputStreamReader;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;
        import com.dapeng.springboot.api.UserServiceSuperCodec.*;

        /**
        * Autogenerated by Dapeng-Code-Generator (2.2.0)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *
        **/
        public class UserServiceCodec {

        
            public static class sayHello<I extends com.dapeng.springboot.api.service.UserService> extends SoaFunctionDefinition.Sync<I, sayHello_args, sayHello_result>
            {
              public sayHello()
              {
                super("sayHello", new SayHello_argsSerializer(),  new SayHello_resultSerializer());
              }

              @Override
              public sayHello_result apply(I iface, sayHello_args sayHello_args) throws SoaException
              {
                sayHello_result result = new sayHello_result();
                
                result.setSuccess(iface.sayHello(sayHello_args.getName()));
                
                return result;
              }

            }
          
            public static class getUser<I extends com.dapeng.springboot.api.service.UserService> extends SoaFunctionDefinition.Sync<I, getUser_args, getUser_result>
            {
              public getUser()
              {
                super("getUser", new GetUser_argsSerializer(),  new GetUser_resultSerializer());
              }

              @Override
              public getUser_result apply(I iface, getUser_args getUser_args) throws SoaException
              {
                getUser_result result = new getUser_result();
                
                result.setSuccess(iface.getUser(getUser_args.getId()));
                
                return result;
              }

            }
          

        public static class getServiceMetadata<I extends com.dapeng.springboot.api.service.UserService> extends SoaFunctionDefinition.Sync<I, getServiceMetadata_args, getServiceMetadata_result> {
          public getServiceMetadata() {
            super("getServiceMetadata", new GetServiceMetadata_argsSerializer(), new GetServiceMetadata_resultSerializer());
          }

          @Override
          public getServiceMetadata_result apply(I iface, getServiceMetadata_args args) {
            getServiceMetadata_result result = new getServiceMetadata_result();

            try (InputStreamReader isr = new InputStreamReader(UserServiceCodec.class.getClassLoader().getResourceAsStream("com.dapeng.springboot.api.service.UserService.xml"));
            BufferedReader in = new BufferedReader(isr)) {
              int len = 0;
              StringBuilder str = new StringBuilder("");
              String line;
              while ((line = in.readLine()) != null) {

                if (len != 0) {
                  str.append("\r\n").append(line);
                } else {
                  str.append(line);
                }
                len++;
              }
              result.setSuccess(str.toString());

            } catch (Exception e) {
              e.printStackTrace();
              result.setSuccess("read metadata failed:" + e.toString());
            }

            return result;
          }

        }


        public static class echo<I extends com.dapeng.springboot.api.service.UserService> extends SoaFunctionDefinition.Sync<I, echo_args, echo_result> {
          public echo() {
            super("echo", new echo_argsSerializer(), new echo_resultSerializer());
          }

          @Override
          public echo_result apply(I iface, echo_args args) {
            echo_result result = new echo_result();

            String echoMsg = (String) TransactionContext.Factory.currentInstance().getAttribute("container-threadPool-info");
            //result.setSuccess("PONG");
            result.setSuccess(echoMsg);
            return result;

          }

        }


        @SuppressWarnings("unchecked")
        public static class Processor<I extends com.dapeng.springboot.api.service.UserService> extends SoaServiceDefinition<com.dapeng.springboot.api.service.UserService>
        {

          public Processor(com.dapeng.springboot.api.service.UserService iface, Class<com.dapeng.springboot.api.service.UserService> ifaceClass)
          {
            super(iface, ifaceClass, buildMap(new java.util.HashMap<>()));
          }

          @SuppressWarnings("unchecked")
          private static <I extends com.dapeng.springboot.api.service.UserService> java.util.Map<String, SoaFunctionDefinition<I, ?, ?>> buildMap(java.util.Map<String, SoaFunctionDefinition<I, ?, ?>> processMap)
          {
            
                processMap.put("sayHello", new sayHello());
              
                processMap.put("getUser", new getUser());
              
            processMap.put("getServiceMetadata", new getServiceMetadata());
            processMap.put("echo", new echo());
            return processMap;
          }
        }

      }
      